import type { GR } from "./data";

const PREFIX = "make-server-210cf10a";

interface Conn {
  base: string;
  anon: string;
}

// The Supabase project info file is autogenerated by Make at runtime.
// Import it dynamically so the app still builds/runs if it is absent.
let connPromise: Promise<Conn | null> | null = null;
function getConn(): Promise<Conn | null> {
  if (!connPromise) {
    connPromise = (async () => {
      try {
        const infoPath = "../utils/supabase/" + "info";
        const info = await import(/* @vite-ignore */ infoPath);
        const projectId = info.projectId as string;
        const publicAnonKey = info.publicAnonKey as string;
        if (!projectId || !publicAnonKey) return null;
        return {
          base: `https://${projectId}.supabase.co/functions/v1/${PREFIX}`,
          anon: publicAnonKey,
        };
      } catch {
        return null;
      }
    })();
  }
  return connPromise;
}

/** True when a Supabase backend is reachable. */
export async function hasBackend(): Promise<boolean> {
  return (await getConn()) !== null;
}

async function req<T>(
  path: string,
  init?: RequestInit,
): Promise<T> {
  const conn = await getConn();
  if (!conn) throw new Error("No backend");
  const res = await fetch(`${conn.base}${path}`, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${conn.anon}`,
      ...(init?.headers ?? {}),
    },
  });
  if (!res.ok) throw new Error(`Request failed: ${res.status}`);
  return (await res.json()) as T;
}

export const api = {
  async list(): Promise<GR[]> {
    const { grs } = await req<{ grs: GR[] }>("/grs");
    return grs;
  },
  async create(gr: GR): Promise<void> {
    await req("/grs", { method: "POST", body: JSON.stringify(gr) });
  },
  async bulk(grs: GR[]): Promise<void> {
    await req("/grs/bulk", { method: "POST", body: JSON.stringify({ grs }) });
  },
  async update(gr: GR): Promise<void> {
    await req(`/grs/${encodeURIComponent(gr.id)}`, {
      method: "PUT",
      body: JSON.stringify(gr),
    });
  },
  async remove(id: string): Promise<void> {
    await req(`/grs/${encodeURIComponent(id)}`, { method: "DELETE" });
  },
};
